[theme]
primaryColor="#4CAF50"
backgroundColor="#f5f7f9"
secondaryBackgroundColor="#ffffff"
textColor="#262730"
font="sans serif"

[server]
maxUploadSize=10
enableXsrfProtection=true

[browser]
gatherUsageStats=false
